name: USCIS Appointment Checker

on:
  schedule:
    - cron: "0 */6 * * *"   # run every 2 hours
  workflow_dispatch:         # allow manual trigger
  
permissions:
  contents: write   # <-- allow pushing to repo

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run USCIS checker
        run: python uscis_checker.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add appointments.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update USCIS appointments [skip ci]"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
